language: node_js
node_js:
  - "6"
  - "4"
install:
  - npm install -g npm@3
  - npm install -g coveralls
  - npm install

script:
  # Both test & coverage.
  - npm run travis
  - coveralls < ./coverage/lcov.info || true # ignore coveralls error

# Allow Travis tests to run in containers.
sudo: false
