language: node_js
node_js:
  - "4"
  - "6"
  - "7"

cache:
  directories:
    - $HOME/.npm

install:
  - npm install -g npm@4
  - npm install -g coveralls
  - npm install

script:
  # Both test & coverage.
  - npm run travis
  - coveralls < ./coverage/lcov.info || true # ignore coveralls error

# Allow Travis tests to run in containers.
sudo: false
