title: Apollo Server
propertytitle: Using Apollo Server
subtitle: Apollo Server
description: A guide to using Apollo Server.
versions:
  - '1'
sidebar_categories:
  null:
    - index
    - why-apollo
    - getting-started
    - whats-new
  Essentials:
    - essentials/building-schema
    - essentials/queries
    - essentials/mutations
  Schema Development:
    - schemas/types
    - schemas/resolvers
    - schemas/context
    - schemas/organizing-code
  Running a Server:
    - server/index
    - server/middleware
    - server/queries
    - server/engine
    - server/secrets
  Best Practices:
    - best-practices/authentication
    - best-practices/schema-design
    - best-practices/subscriptions
    - best-practices/performance
    - best-practices/caching
    - best-practices/monitoring
    - best-practices/versioning
    - best-practices/schema-stitching
    - best-practices/infrastructure
    - best-practices/deploying
  Working with Backends:
    - backends/general
    - backends/sql
    - backends/mongodb
    - backends/rest
    - backends/prisma
  API Reference:
    - api/apollo-server
    - api/graphql-subscriptions
    - api/apollo-engine

github_repo: apollographql/apollo-server
content_root: docs/source

typescript_api_box:
  data_file: docs.json

url: https://www.apollographql.com/docs/apollo-server/
root: /docs/apollo-server/

public_dir: public/docs/apollo-server
