title: Apollo Server
propertytitle: Using Apollo Server
subtitle: Apollo Server
description: A guide to using Apollo Server.
versions:
  - '1'
  - '2'
sidebar_categories:
  null:
    - index
    - getting-started
    - whats-new
  Essentials:
    - essentials/schema
    - essentials/server
    - essentials/data
    - essentials/querying
  Deployment:
    - deployment/index
    - deployment/heroku
    - deployment/lambda
  Advanced:
    - advanced/scalars-enums
  Features:
    - features/introduction
    - features/remote-schemas
    - features/schema-delegation
    - features/schema-transforms
  API Reference:
    - api/apollo-server
    - api/graphql-subscriptions
    - api/apollo-engine
    - title: graphql-tools
      url: https://www.apollographql.com/docs/graphql-tools

github_repo: apollographql/apollo-server
content_root: docs/source

typescript_api_box:
  data_file: docs.json

url: https://www.apollographql.com/docs/apollo-server/
root: /docs/apollo-server/

public_dir: public/docs/apollo-server
